[project]
name = "nd_aligner"
version = "0.5.0"
description = "ND-Aligner"
readme = "README.md"
requires-python = ">=3.14,<3.15"
authors = [{ name = "Suseong Kim", email = "blue29591@postech.ac.kr" }]
dependencies = [
  "dacite~=1.9",
  "einops~=0.8.2",
  "g2p-en~=2.1",
  "inflect~=7.5",
  "librosa~=1.0",
  "matplotlib~=3.11",
  "ninja~=1.13",
  "nltk~=3.10",
  "noisereduce~=3.0",
  "numpy~=2.5",
  "nvidia-cuda-cccl==13.0.85",
  "nvidia-cuda-crt==13.0.88",
  "nvidia-cuda-nvcc==13.0.88",
  "nvidia-nvvm==13.0.88",
  "onnxruntime-gpu~=1.29",
  "phonemizer~=3.4",
  "praatio~=6.2",
  "resemblyzer~=0.1.4",
  "scipy~=1.18",
  "silero-vad~=6.2",
  "soundfile~=0.14.0",
  "tensorboard~=2.21",
  "textgrid~=1.6",
  "torch==2.13.0",
  "tqdm~=4.70",
  "unidecode~=1.4",
]

[dependency-groups]
dev = ["black~=26.5", "ipykernel~=7.3", "isort~=9.0", "pandas~=3.0", "pyright~=1.1"]

[build-system]
requires = ["uv_build>=0.9.11,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
required-version = ">=0.9.11"
keyring-provider = "subprocess"
reinstall-package = ["onnxruntime-gpu"]

[tool.uv.build-backend]
module-name = "nd_aligner"
module-root = ""
source-exclude = []

[tool.black]
line-length = 100
target-version = ["py314"]

[tool.pyright]
include = ["nd_aligner"]
pythonVersion = "3.14"
pythonPlatform = "Linux"
deprecateTypingAliases = true
typeCheckingMode = "basic"
reportPropertyTypeMismatch = "error"
reportFunctionMemberAccess = "error"
reportImportCycles = "warning"
reportUnusedClass = "error"
reportUnusedFunction = "error"
reportUnusedVariable = "error"
reportDuplicateImport = "error"
reportUntypedFunctionDecorator = "warning"
reportUntypedClassDecorator = "warning"
reportUntypedBaseClass = "warning"
reportUntypedNamedTuple = "warning"
reportPrivateUsage = "error"
reportTypeCommentUsage = "error"
reportConstantRedefinition = "error"
reportDeprecated = "error"
reportUninitializedInstanceVariable = "warning"
reportMissingParameterType = "warning"
reportMissingTypeArgument = "warning"
reportUnnecessaryIsInstance = "error"
reportUnnecessaryCast = "error"
reportUnnecessaryComparison = "error"
reportUnnecessaryContains = "error"
reportImplicitStringConcatenation = "warning"
reportUnusedExpression = "warning"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMatchNotExhaustive = "error"
reportImplicitOverride = "error"
reportInvalidStringEscapeSequence = "none"

[tool.isort]
profile = "black"
line_length = 100
